name: Blank Issue
description: Create a blank issue for anything else
title: ""
labels: []
body:
    - type: markdown
      attributes:
          value: |
              Please provide as much detail as possible about your issue or question.
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Describe your issue, question, or feedback
          placeholder: Tell us what's on your mind...
      validations:
          required: true
