name: Feature Request
description: Suggest a new feature or enhancement for the package
title: "[Feature]: "
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to suggest a new feature! Please fill out the details below.
    - type: textarea
      id: feature-description
      attributes:
          label: Feature Description
          description: Describe the feature you'd like to see added
          placeholder: I would like to have X feature because...
      validations:
          required: true
    - type: textarea
      id: use-case
      attributes:
          label: Use Case
          description: Explain how this feature would be useful and what problem it solves
          placeholder: This would help me to...
      validations:
          required: true
    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed Solution
          description: If you have an idea of how this could be implemented, please share it
          placeholder: This could be implemented by...
      validations:
          required: false
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: Have you considered any alternative solutions or workarounds?
          placeholder: I've tried X but...
      validations:
          required: false
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, or examples about the feature request
      validations:
          required: false
